[/Script/EngineSettings.GameMapsSettings]
; 어떤 레벨에서 Play 하더라도 우리 C++ GameMode가 적용되도록 전역 기본값으로 지정
; → GameMode::BeginPlay 에서 Test 모듈의 ATestActor가 스폰된다
GlobalDefaultGameMode=/Script/ModuleAndPlugin.ModuleAndPluginGameMode

[/Script/Engine.RendererSettings]
r.GenerateMeshDistanceFields=True
r.DynamicGlobalIlluminationMethod=1
r.ReflectionMethod=1

[/Script/WindowsTargetPlatform.WindowsTargetSettings]
DefaultGraphicsRHI=DefaultGraphicsRHI_DX12

[/Script/AndroidFileServerEditor.AndroidFileServerRuntimeSettings]
bEnablePlugin=True
bAllowNetworkConnection=True
SecurityToken=EC16415F41F87D28B1B2B4A427754A6E
bIncludeInShipping=False
bAllowExternalStartInShipping=False
bCompileAFSProject=False
bUseCompression=False
bLogFiles=False
bReportStats=False
ConnectionType=USBOnly
bUseManualIPAddress=False
ManualIPAddress=

